# Generated by Django 5.2.17 on 2026-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"Size": ["S", "M", "L"], "Color": ["Red", "Blue"]}'),
        ),
    ]
